nelmio_api_doc:
    documentation:
        info:
            title: '%app.name%'
            description: Platform for restaurant management automation
            version: latest
    areas:
        path_patterns:
            - ^/api(?!/doc$)
