
services:
    app:
        image: taranovegor/pet.restaurateur:latest
        restart: on-failure
        depends_on:
            - database

    database:
        image: postgres:17-alpine
        restart: on-failure
        healthcheck:
            test: [ "CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-usr}" ]
            timeout: 5s
            retries: 5
            start_period: 60s
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-app}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-psw}
            POSTGRES_USER: ${POSTGRES_USER:-usr}
        volumes:
            - database_data:/var/lib/postgresql/data/:rw

volumes:
    database_data: ~
