name: Tests

on:
    pull_request:
        branches: ['master']

jobs:
    tests:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker
              uses: docker/setup-buildx-action@v3

            - name: Set up Docker Compose
              run: |
                  sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" \
                    -o /usr/local/bin/docker-compose
                  sudo chmod +x /usr/local/bin/docker-compose

            - name: Set APP_UID and APP_GID
              run: |
                  echo "APP_UID=$(id -u)" >> $GITHUB_ENV
                  echo "APP_GID=$(id -g)" >> $GITHUB_ENV

            - name: Build Docker containers
              run: make build

            - name: Run application with Makefile
              run: |
                  make up
                  ./composer.sh install

            - name: Check style
              run: make check-style

            - name: Run tests (PHPUnit)
              run: make tests-run
